image: ubuntu:18.04

variables:
  GIT_SSL_NO_VERIFY: "true"

buildjob:
  before_script:
    - echo "deb http://ports.ubuntu.com/ubuntu-ports/ bionic main restricted universe multiverse" >> /etc/apt/sources.list
    - echo "deb http://ports.ubuntu.com/ubuntu-ports/ bionic-security main restricted universe multiverse" >> /etc/apt/sources.list
    - echo "deb http://ports.ubuntu.com/ubuntu-ports/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list
    - apt-get update && apt-get upgrade -yy
    - apt-get install -y build-essential crossbuild-essential-arm64 debhelper

  script:
    - cd $CI_PROJECT_DIR/libgig
    - apt-get install -y libsndfile1-dev:arm64 doxygen:arm64 uuid-dev:arm64 libsqlite3-dev:arm64
    - dpkg-buildpackage -aarm64 -rfakeroot -b
